/*----------------------------------------------------------------------------*/
/* Copyright (c) 2017-2018 FIRST. All Rights Reserved.                        */
/* Open Source Software - may be modified and shared by FRC teams. The code   */
/* must be accompanied by the FIRST BSD license file in the root directory of */
/* the project.                                                               */
/*----------------------------------------------------------------------------*/




package org.usfirst.frc.team7224.robot;



import com.ctre.phoenix.motorcontrol.can.WPI_TalonSRX;
import com.ctre.phoenix.motorcontrol.can.WPI_VictorSPX;

//import com.ctre.phoenix.motorcontrol.can.TalonSRX;
//import com.ctre.phoenix.*;
import edu.wpi.first.wpilibj.Compressor;
import edu.wpi.first.wpilibj.Solenoid;
import edu.wpi.first.wpilibj.ADXRS450_Gyro;
import edu.wpi.first.wpilibj.Encoder; 
import edu.wpi.first.wpilibj.DigitalInput;

// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers

 * floating around.
 */
public class RobotMap {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static Solenoid pneumaticsSolenoid0 = new Solenoid(0, 0);  // Shifter
    public static Compressor pneumaticsCompressor = new Compressor(0);
    public static WPI_VictorSPX chassisTalonSPX6  = new WPI_VictorSPX(6); 
    public static WPI_VictorSPX chassisTalonSPX5  = new WPI_VictorSPX(5); 
    public static WPI_VictorSPX chassisTalonSPX4 = new WPI_VictorSPX(4);
    public static WPI_VictorSPX chassisTalonSPX3 = new WPI_VictorSPX(3);
    public static WPI_VictorSPX chassisTalonSPX2 = new WPI_VictorSPX(2);
    public static WPI_VictorSPX chassisTalonSPX1 = new WPI_VictorSPX(1);
    public static WPI_TalonSRX turnTalonSRX8 = new WPI_TalonSRX(8);
    public static WPI_TalonSRX shootTalonSRX11 = new WPI_TalonSRX(11);
    public static WPI_TalonSRX shootTalonSRX10  = new WPI_TalonSRX(10);
    public static WPI_VictorSPX elvVictorSPX7  = new WPI_VictorSPX(7); 
    public static WPI_TalonSRX intakeTalonSRX9  = new WPI_TalonSRX(9); 
    public static WPI_VictorSPX hookVictorSPX12  = new WPI_VictorSPX(12); 
    public static WPI_TalonSRX winchTalonSPX14  = new WPI_TalonSRX(14); 
    public static WPI_TalonSRX winchTalonSPX15  = new WPI_TalonSRX(15); 
    public static WPI_TalonSRX wheelTalonSRX13  = new WPI_TalonSRX(13);
	public static Encoder rigthEncoder = new Encoder(new DigitalInput(0), new DigitalInput(1), false, Encoder.EncodingType.k4X);
	public static Encoder leftEncoder = new Encoder(new DigitalInput(2), new DigitalInput(3), true, Encoder.EncodingType.k4X);
    public static ADXRS450_Gyro spiGyro_1  = new ADXRS450_Gyro();
  
}
